name: EclipticEngineering
version: '${project.version}'
main: org.wolflink.minecraft.plugin.eclipticengineering.EclipticEngineering
api-version: '1.20'
authors: [MikkoAyaka]
depend:
  - EclipticStructure
  - WolfirdFramework
  - Citizens
  - ProRPGItems
commands:
  ee-build:
    aliases: eeb
  ee-ability:
    aliases: eea
  ee-stage:
    aliases: ees
  ee-vote:
    aliases: eev
  ee-gamestructure:
    aliases: eegs
  ee-resource:
    aliases: eer
  ee-forge:
    aliases: eef